name: fuel_shocks_intelligence
version: "1.0"
config-version: 2

profile: fuel_shocks_intelligence

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  fuel_shocks_intelligence:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
